### PR TITLE
#435 - Download Report Log" option does not work from Help Menu

### LINKED ISSUE #435: "Download Report Log" option does not work from Help Menu
This is occurring on Version 8.0.3 Build 111

Behavior:  When I click on "Download Report Log" from the Designer component - Layout - Help Menu, I expect a report to be generated.  The only thing that happens is that a browser tab opens up with "Untitled" on the tab and no information on the screen:

image-2022-02-23-08-22-54-981

There is no log error in the Console. Nothing was downloaded to the file system.

Steps to reproduce:
1) Open Design Component
2) Select a Template to edit
3)  Go to Layout tab
4) Hover over the On Help menu dropdown.
5)  Select "Download Report Log"

### PR DESCRIPTION
**Pull request by ramdev1980**

### CODE REVIEW

File: projects/sitemanage/src/main/java/com/percussion/sitemanage/importer/PSSiteImportLogViewer.java [hunk 1]
```diff
@@ -106,68 +106,69 @@ protected void doGet(HttpServletRequest request, HttpServletResponse response) t
                     return;
                 }
             }
-
+            /*
             if (logs == null || logs.isEmpty()) {
```
Comment (natechadwick) [inline projects/sitemanage/src/main/java/com/percussion/sitemanage/importer/PSSiteImportLogViewer.java]: @ramdev1980 please remove the commented out code

File: projects/sitemanage/src/main/java/com/percussion/sitemanage/importer/PSSiteImportLogViewer.java [hunk 2]
```diff
@@ -106,68 +106,69 @@ protected void doGet(HttpServletRequest request, HttpServletResponse response) t
...
+                }
 
-            // now write out each page's log
-            if (pageLogIds != null) {
-                for (Long pageLogId : pageLogIds) {
-                    PSImportLogEntry pageLog = logDao.findLogEntryById(pageLogId);
-                    if (pageLog != null) {
-                        out.println(pageLog.getLogData());
+                // now write out each page's log
+                if (pageLogIds != null) {
```
Comment (natechadwick) [inline projects/sitemanage/src/main/java/com/percussion/sitemanage/importer/PSSiteImportLogViewer.java]: What if pageLogIds is empty?

**Review by natechadwick — CHANGES_REQUESTED** [review]

**Review by natechadwick — APPROVED** [review]
