### PR TITLE
#832 Session doesn't time out and User session extension option also …

### LINKED ISSUE #832: Session doesn't time out and User session extension option also not available to user application wide
**Describe the bug**
When user session times out , the pop up for extending the user session not available to user. And also session doesn't time out.

**To Reproduce**

Go to Widget Builder  (http://localhost:9992/cm/app/?view=widgetbuilder&pathType=unknown)
Leave the screen idle for the same duration which configured under <userSessionTimeout> tag in Config.xml file.
Session doesn't time out and Pop up for extending session not available to user 

**Expected behavior**
Session should time out after the screen is left idle for the interval specified  in Config.xml file gets over and a popup for extending session should appear.

**Additional context**
Navigate all the options available for similar issue and fix.

### PR DESCRIPTION
**Pull request by ramdev1980**
…not available to user application wide

### CODE REVIEW

File: WebUI/war/plugins/perc_sessionTimeout.js [hunk 1]
```diff
@@ -193,215 +115,81 @@
...
-        $(document).on("keypress",function () {
-            userActivity();
-        });
-
-        // Initial sync of status
-        syncLast();
-        updateServerStatus(true);
-
-        var serverInterval = setInterval(timerIncrement, 1000); // 1 second
+        var serverInterval = setInterval(trackSession, 1000); // 1 second
```
Comment (natechadwick) [inline WebUI/war/plugins/perc_sessionTimeout.js]: @ramdev1980  What is this doing every second?

File: system/src/main/java/com/percussion/servlets/PSSessionCheckServlet.java [hunk 2]
```diff
@@ -0,0 +1,49 @@
...
+import javax.servlet.http.HttpServlet;
+import javax.servlet.http.HttpServletRequest;
+import javax.servlet.http.HttpServletResponse;
+import java.io.IOException;
+
+public class PSSessionCheckServlet extends HttpServlet {
+
+    @Override
+    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
+        //super.doGet(req, resp);
```
Comment (natechadwick) [inline system/src/main/java/com/percussion/servlets/PSSessionCheckServlet.java]: Please remove commented code.

File: WebUI/war/services/PercServiceUtils.js [hunk 3]
```diff
@@ -282,7 +282,7 @@
         makeAjaxRequest(args);
     }
     function makeAjaxRequest(args){
```
Comment (natechadwick) [inline WebUI/war/services/PercServiceUtils.js:284]: @ramdev1980  Does this cover all of the ajax calls?  There are a number of methods  on this plugin that I would expect to see toggle the client side timeout.

**Review by natechadwick — CHANGES_REQUESTED** [review]
@ramdev1980  Some questions / changes.

**Review by natechadwick — APPROVED** [review]
lgtm
