### PR TITLE
#437-The Stacked / Side by Side dropdown is always greyed out

### LINKED ISSUE #437: The Stacked / Side by Side dropdown is always greyed out.
This was reproduced on Version 8.0.3 Build 113

Behavior:
When testing the Design Inspector and the drop down arrow for the Stacked or Side by Side options.  The options are always greyed out.  I have tested this on every template.

image-2022-02-24-13-13-03-822

Steps to reproduce.
1) Select a template to Edit in Design
2) Click on the Design Inspector
3)  Highlight a region that is editable.
4)  Click on the sidebar button next to Design Inspector. 
5)  All options are greyed out.

### PR DESCRIPTION
**Pull request by ramdev1980**

### CODE REVIEW

File: WebUI/war/views/PercInspectionToolHandler.js [hunk 1]
```diff
@@ -416,7 +434,7 @@
                 }
                 widgetDiv.attr('ownerId', tempContent.ownerid);
                 if (tempContent.isTransparent) {
-                    widgetDiv.addClass('perc-widget-transperant');
+                    widgetDiv.addClass('perc-widget-transparent');
```
Comment (natechadwick) [inline WebUI/war/views/PercInspectionToolHandler.js:437]: @ramdev1980 Is this referenced anywhere else?  You probably need to update other css / js if they were using the misspelled class name too right?

**Review by natechadwick — CHANGES_REQUESTED** [review]

File: WebUI/war/views/PercInspectionToolHandler.js (hunk 1 above)
Comment (ramdev1980) [reply WebUI/war/views/PercInspectionToolHandler.js:437]: @natechadwick  I pushed 4 more related files, based on your suggestion. Please review.

**Review by natechadwick — APPROVED** [review]
